#!/usr/bin/env python3
"""Live fix: repair a theme that already passed its gate, without converting
again (SKILL.md "Live fix").

  live-fix.py start   --workspace WS [--mode flash|full] [--report PATH] [--input DIR]
  live-fix.py log     --workspace WS --note TEXT [--script-review PATH=REASON ...]
  live-fix.py revert  --workspace WS --to N          (N fixes kept; 0 = the base)
  live-fix.py status  --workspace WS
  live-fix.py check   --workspace WS [--wp-cli PREFIX | --env .test-env-<slug>.json]
  live-fix.py certify --workspace WS  --wp-cli PREFIX | --env .test-env-<slug>.json [--state PATH]
  live-fix.py check-path --workspace WS --path P [--path P ...] [--content-file F (one --path)]
  live-fix.py verify-package --workspace WS [--report PATH] [--quick PATH] [--state PATH]
  live-fix.py deliver --workspace WS --zip PATH [--report PATH] [--quick PATH] [--state PATH]
  live-fix.py guard   --workspace WS
  live-fix.py discard --workspace WS
  live-fix.py levers

The workspace theme ({workspace}/theme/<slug>) stays the only truth: the fix
is an edit of its files (content in content/*.json, in the bundle's own
tokenized form), the preview receives it through `install` (upload plus the
guarded re-import), and the ZIP is packed from it. What a live fix may never
touch is enforced here, not by convention:
  - the files the converter owns (functions.php, inc/, the runtime assets):
    a bug there is a converter gap, reported and fixed in the converter;
  - the inputs of the conversion (source, dist, manifest, block plan): a
    change there is a re-conversion, which discards the live fixes;
  - a changed script needs Flash's script scan (Flash) or a recorded review
    (full), as when the conversion listed it;
  - changed block markup must keep the block grammar (delimiters that parse,
    open and close in order, attributes one JSON object).

{workspace}/live-fix.json is the mark: the base the fixes start from, and the
log of every fix; .live-fix/objects/ keeps every version it names, so any fix
can be reverted. `check` measures a preview (live-fix-check.json); `certify`
measures the fresh install the delivery is certified on (live-fix-state.json),
bound by the liveDigest that packaging recomputes. Every refusal carries its
code and the lever that clears it (`levers` lists them all). Output is JSON on
stdout; exit 1 on a refusal.
"""
import argparse
import hashlib
import html
from html.parser import HTMLParser
import importlib.util
import json
import os
from pathlib import Path
import re
import shlex
import shutil
import subprocess
import sys
import time
import zipfile

SCHEMA = 'h2wp-live-fix/1'
STATE_SCHEMA = 'h2wp-live-fix-state/1'
MARKER = 'live-fix.json'
STATE = 'live-fix-state.json'   # the certifying check (fresh install)
CHECK = 'live-fix-check.json'   # the last check of a preview; certifies nothing
STORE = '.live-fix'
REASON = 12  # the shortest note or review that says anything (as a ledger resolution)
HERE = Path(__file__).resolve().parent

# The Gutenberg runtime the compiler copies into every theme
# (server/core/templates/gutenberg; tools/test-live-fix.py keeps the two equal).
GUTENBERG_RUNTIME = frozenset({
    'element-allowlist.json',
    'assets/gutenberg-blocks.js', 'assets/gutenberg-commerce.css', 'assets/gutenberg-commerce.js',
    'assets/gutenberg-editor-canvas.js', 'assets/gutenberg-editor-frame.js', 'assets/gutenberg-editor-position.css',
    'assets/gutenberg-editor.css', 'assets/gutenberg-fields.css', 'assets/gutenberg-forms.js',
    'assets/gutenberg-navigation.css', 'assets/gutenberg-related.js', 'assets/gutenberg-wizard.css',
    'assets/gutenberg-wizard.js',
})
# Derived by the compiler, never authored: its per-page projection of the
# editor canvas, and the bridge from the source's variables to the presets.
EDITOR_POSITION = re.compile(r'assets/(gutenberg-editor-position-[a-z0-9-]+\.css|editor-position/.+|gutenberg-token-bridge\.css)')
# The HTML runtime make-theme.mjs emits, and the recorded reveal rules.
HTML_RUNTIME = re.compile(r'assets/(html2wp-runtime/.+|spa-reveals\.css)')
# The recorder's runtime (prerender-spa.py), wherever the theme carries it:
# known by the header it is generated with (gutenberg-plan.py RECORDER_RUNTIME).
RECORDER = b'/* spa-runtime.js \xe2\x80\x94 generated by html2wp-sub prerender-spa.py.'
# The contract config the compiler writes: which sheets and scripts load where.
GUTENBERG_CONTRACT = frozenset({'content/config.json', 'content/block-styles.json'})

# What a live fix may add or change, per target: the site's own templates,
# parts, content, styles, scripts and media. Nothing else reaches a customer's
# WordPress through a live fix: no PHP (a block theme includes every
# patterns/*.php; a .php under assets is served and run by URL), no server
# configuration, no other file type.
SITE_EXTENSIONS = r'\.(css|js|png|jpe?g|gif|webp|avif|svg|ico|bmp|woff2?|ttf|otf|eot|mp4|webm|ogv|ogg|mp3|wav|m4a|pdf)'
SITE_ASSET = re.compile(r'assets/.+' + SITE_EXTENSIONS, re.I)
# The HTML target keeps the site's own files where the source had them
# (css/style.css, js/custom.js, img/…, a root app.js): any folder but the
# theme's own.
HTML_SITE_ASSET = re.compile(r'(?!(inc|templates|parts|patterns|clara-content|languages)/).+' + SITE_EXTENSIONS, re.I)
EDITABLE = {
    'gutenberg': re.compile(r'(templates|parts)/[^/]+\.html|content/(content|patterns|assets)\.json|theme\.json|style\.css|screenshot\.png'),
    'html': re.compile(r'(templates|parts)/[^/]+\.html|patterns/[^/]+\.php|clara-content/.+\.(json|html)|theme\.json|style\.css|readme\.txt|screenshot\.png'),
}
# The only PHP a pattern file may hold: the generator's own guard and its
# theme-URL echo (make-theme.mjs), around markup. Anything else is code.
SAFE_PHP = frozenset({"defined( 'ABSPATH' ) || exit;", 'echo esc_url( get_template_directory_uri() );',
                      '= esc_url( get_template_directory_uri() )', '= esc_url( get_template_directory_uri() );'})
# Every PHP opening a server may honour: <?php, <?=, and the short <? (on
# wherever short_open_tag is, PHP's built-in default).
PHP_BLOCK = re.compile(r'<\?(?:php\b)?(.*?)(?:\?>|\Z)', re.S | re.I)
# A link or source an element may carry (as the runtime saves it).
SAVED_URL = re.compile(r'(?:https?:|mailto:|tel:|#|/|\.{0,2}/|asset:|page:|category:|[a-z0-9._-]+(?:/|$))[^\x00-\x20\x7f]*', re.I)
# Styles that load from another origin (tracking, exfiltration through CSS),
# found once CSS escapes are decoded.
EXTERNAL_CSS = re.compile(r'@import\b[^;{}]*;?|url\(\s*[\'"]?\s*(?:https?:|//)[^)]*\)', re.I)
SLUG = re.compile(r'[a-z0-9][a-z0-9-]{0,63}')
# The wp-cli prefixes live-fix.py runs: the app runtime's, or a test-env
# container's (test-env.sh). Nothing else reads a preview for a certification.
WP_CLI_SHAPES = re.compile(r'php /opt/wp-cli\.phar --path=/var/www/html --allow-root|docker exec h2wpd?-[a-z0-9-]+-wp-1 wp --allow-root')
ZIP_BYTES, ZIP_MEMBERS = 2 * 1024 ** 3, 50000

# Every refusal by its code, with the lever that clears it: a stable list the
# app shows verbatim. The message says what and where.
LEVERS = {
    'no-workspace': 'Pass the workspace the conversion ran in (the folder of conversion-manifest.json).',
    'no-theme': 'Convert first: a live fix repairs a theme that exists.',
    'symlink': 'Replace the symbolic link with the file itself.',
    'not-live': 'Start the live fix first: live-fix.py start.',
    'marker': 'Restore live-fix.json, or discard the live fixes (live-fix.py discard).',
    'delivered': 'The last live fix was delivered; start the next one: live-fix.py start.',
    'changed-after-delivery': 'Restore the delivered theme from its ZIP, or discard the live fixes and convert again.',
    'no-base': 'Run the gate of this theme first (full: the full check; Flash: the quick check; HTML: gates B/C, or the finishing pass\'s green F1 round for --base f1). A live fix starts from a theme that passed.',
    'compiler-owned': 'Revert these files. A bug there is a converter gap: report it (POST /v1/report); it is fixed in the converter, and converting again then discards the live fixes.',
    'inputs-changed': 'Restore them: a live fix edits only the theme. To change the source or the block plan, discard the live fixes and convert again.',
    'unlogged': "Record the change: live-fix.py log --note '<what was wrong and what the fix does>'.",
    'note': 'Write a note of at least 12 characters: what was wrong and what the fix does.',
    'nothing': 'Edit the theme first, then record the fix.',
    'script-review': "Read the whole script, then record its review: live-fix.py log --note '<fix>' --script-review <path>='<what it does, why it is safe>'.",
    'script-scan': 'Revert the script: Flash lists only scripts its scan accepts. Full check & build reviews it instead.',
    'block-grammar': 'Repair the block markup: every <!-- wp:name --> opened is closed in order, and its attributes are one JSON object. Change a block through its attributes and its HTML together (an h2wp/element keeps its text in both).',
    'file-type': 'Remove it. A live fix changes the site\'s templates, parts, theme.json, style.css, content bundle, screenshot, and its own stylesheets, scripts, images, fonts and media; never PHP, server configuration or other file types.',
    'unsafe-markup': 'Remove what the fix added. A live fix never adds a script, an event handler, a javascript: URL, an iframe, a Custom HTML block or PHP to markup; behaviour comes from the converter, reviewed.',
    'php': 'Keep a pattern file to markup: its PHP header stays as generated, and its only other PHP is the generator\'s theme-URL echo.',
    'element': 'Give the element only a tag and attributes the converter emits (element-allowlist.json), and links WordPress saves: http(s), mailto:, tel:, #, a path, or a page:/asset: token.',
    'external-css': 'Remove the @import or url() to another origin: the site loads its styles and assets from the theme.',
    'style-header': 'Restore the style.css header: a live fix may change its Version and Description, nothing else (the theme\'s name and text domain identify it).',
    'slug': 'The workspace names its theme by a slug of lowercase letters, digits and hyphens; restore conversion-manifest.json and live-fix.json.',
    'store': 'A stored version was changed; revert cannot trust it. Restore the theme from its ZIP or discard the live fixes.',
    'revert': 'Name a fix that exists: live-fix.py revert --to <0 for the base, up to the number of fixes>.',
    'env': "Pass the preview's wp-cli: the app runtime's (php /opt/wp-cli.phar --path=/var/www/html --allow-root) or a test-env container's (--env .test-env-<slug>.json).",
    'wp-cli': 'Start the preview, and pass the wp-cli prefix that reaches it.',
    'active-theme': 'Run install: it uploads and activates the theme.',
    'installed-differs': 'Run install: the preview receives the workspace theme and re-imports its content.',
    'screenshot-differs': 'Take the screenshot again (gscreenshot / screenshot), then run install.',
    'import': 'Run install: its guarded re-import brings the preview to this bundle.',
    'owner-edited': 'Certify on a fresh install, where the bundle is all there is. The owner keeps their edits, and their preview receives the fix through the guarded re-import.',
    'db-overrides': 'Certify on a fresh install. A change that belongs in the delivery goes into the theme file (templates/, parts/, theme.json), never into the Site Editor or Styles.',
    'state-stale': 'Certify again on the fresh install (live-fix.py certify), after the last change.',
    'not-certified': 'Certify the fixed theme on a fresh install (live-fix.py certify), and clear what it refuses; or the owner takes it without the check (--uncertified), marked not certified.',
    'certification': 'Run the certifying gate on the fixed theme, on the fresh install (full: the full check, its differences accepted again if rows stay red; Flash: the quick check; HTML: gates B/C, or the host-recorded round; what stays red goes out WITH a ledger, not certified).',
    'zip': 'Package again from the workspace theme.',
    'live-fixes': 'Keep fixing live, or let the owner discard the live fixes (live-fix.py discard keeps them beside the workspace), then convert.',
}


class Refused(Exception):
    """A refusal: what is wrong (the message), and the lever that clears it."""
    def __init__(self, code, message):
        super().__init__(message)
        self.row = row(code, message)


def row(code, message):
    return {'code': code, 'message': message, 'lever': LEVERS[code]}


def compiler_owned(target, rel, head=b''):
    """True for a theme file the converter owns: a live fix must not change
    it. `head` is the start of the file, which names the recorder's runtime."""
    if rel == 'functions.php' or rel.startswith('inc/') or head.startswith(RECORDER) or rel.endswith('/spa-runtime.js') or rel == 'spa-runtime.js':
        return True
    if target == 'gutenberg':
        return rel in GUTENBERG_RUNTIME or rel in GUTENBERG_CONTRACT or bool(EDITOR_POSITION.fullmatch(rel))
    return bool(HTML_RUNTIME.fullmatch(rel))


# A name a server may run, wherever the extension sits in it (x.php.jpg runs
# on an Apache host that maps .php by AddHandler).
RUNNABLE = re.compile(r'\.(php[0-9]?|phtml|phar|pht|phps|shtml|cgi|pl)(\.|$)', re.I)


def editable(target, rel):
    """True for a path a live fix may add or change (compiler_owned aside)."""
    parts = rel.split('/')
    pattern_php = target == 'html' and len(parts) == 2 and parts[0] == 'patterns' and RUNNABLE.findall(parts[1]) == [('php', '')]
    if any(RUNNABLE.search(part) for part in parts) and not pattern_php or any(part.startswith('.') for part in parts):
        return False
    return bool(EDITABLE[target].fullmatch(rel) or SITE_ASSET.fullmatch(rel) or target == 'html' and HTML_SITE_ASSET.fullmatch(rel))


def stored(lay, value):
    """A stored version (by hash), or b''."""
    path = lay['ws'] / STORE / 'objects' / (value or '')
    return path.read_bytes() if value and path.is_file() else b''


def head_of(lay, value):
    """The first bytes of a stored version, for compiler_owned."""
    return stored(lay, value)[:len(RECORDER)]


def php_outside_markup(text, was=''):
    """The PHP in a pattern file beyond the generator's shape, or []: its
    header block stays as it was (a new file: a docblock of `Key: value`
    lines and the ABSPATH guard), and every other PHP block is the
    theme-URL echo."""
    blocks, before = PHP_BLOCK.findall(text), PHP_BLOCK.findall(was)
    if not blocks:
        return []
    found = []
    header = blocks[0]
    if before:
        if header != before[0]:
            found.append('the PHP header changed')
    else:
        doc = re.match(r'\s*/\*\*(.*?)\*/', header, re.S)
        code = ' '.join(header[doc.end():].split()) if doc else None
        if not doc or code != "defined( 'ABSPATH' ) || exit;" or not all(
                re.fullmatch(r'\*(\s+[A-Za-z][A-Za-z ]*:.*)?', line.strip()) for line in doc.group(1).strip().splitlines()):
            found.append('a PHP header other than the generated docblock and ABSPATH guard')
    for block in blocks[1:]:
        statement = ' '.join(block.split())
        if statement not in SAFE_PHP - {"defined( 'ABSPATH' ) || exit;"}:
            found.append(statement[:80])
    return found


# Markup is judged as a browser parses it (html.parser splits attributes on
# `/` and quotes, and decodes entities in values): the features that run code
# in a visitor's browser, each with its text, so a changed one counts as new.
SCRIPT_ELEMENTS = frozenset({'script', 'iframe', 'frame', 'frameset', 'object', 'embed', 'applet', 'base', 'portal'})
URL_ATTRIBUTES = frozenset({'href', 'src', 'action', 'formaction', 'xlink:href', 'data', 'poster', 'background', 'cite',
                            'longdesc', 'srcset', 'ping', 'codebase', 'archive', 'manifest', 'icon', 'lowsrc', 'dynsrc'})
# The schemes a live fix may leave in a URL, once decoded.
SAFE_SCHEME = re.compile(r'(https?|mailto|tel|asset|page|category):|data:image/(png|jpe?g|gif|webp|avif|svg\+xml)[;,]', re.I)
FEATURES = {'element': 'a script, iframe, object, embed or base element (or a meta refresh)', 'handler': 'an on… event handler',
            'url': 'a URL with a script scheme', 'srcdoc': 'srcdoc', 'php': 'PHP', 'css': 'a style loaded from another origin',
            'raw': 'raw HTML outside the blocks'}


def decoded_url(value):
    """A URL as the browser reads it: entities decoded, controls and ASCII
    whitespace dropped."""
    return re.sub(r'[\x00-\x20\x7f]', '', html.unescape(html.unescape(value.strip('\'"'))))


def unsafe_url(value):
    """True for a URL whose scheme a live fix may not introduce."""
    url = decoded_url(value)
    scheme = re.match(r'[a-z][a-z0-9+.-]*:', url, re.I)
    return bool(scheme) and not SAFE_SCHEME.match(url)


def css_loads(text):
    """What CSS loads from another origin (every @import too), with its CSS
    escapes decoded first, as the browser decodes them."""
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
    text = re.sub(r'\\([0-9a-fA-F]{1,6})\s?', lambda m: chr(int(m.group(1), 16)) if int(m.group(1), 16) <= 0x10FFFF else '', text)
    text = re.sub(r'\\(.)', r'\1', text)
    return [match.group(0) for match in EXTERNAL_CSS.finditer(text)]


class Features(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.found, self.raw = [], None

    def handle_starttag(self, tag, attrs):
        pairs = tuple((name, value or '') for name, value in attrs)
        if tag in SCRIPT_ELEMENTS or (tag == 'meta' and any(name == 'http-equiv' for name, _ in pairs)):
            if tag == 'script':
                self.raw = [tag, pairs, []]
            else:
                self.found.append(('element', tag, repr(pairs)))
        elif tag == 'style':
            self.raw = [tag, pairs, []]
        for name, value in pairs:
            if name.startswith('on'):
                self.found.append(('handler', f'{tag} {name}', value))
            elif name == 'srcdoc':
                self.found.append(('srcdoc', tag, value))
            elif name in URL_ATTRIBUTES:
                urls = [c.split()[0] for c in value.split(',') if c.strip()] if name == 'srcset' else [value]
                if any(unsafe_url(url) for url in urls):
                    self.found.append(('url', f'{tag} {name}', value))
            elif name == 'style':
                self.found += [('css', f'{tag} style', load) for load in css_loads(value)]

    def handle_startendtag(self, tag, attrs):
        self.handle_starttag(tag, attrs)
        if self.raw and self.raw[0] == tag:
            self.finish()

    def handle_data(self, data):
        if self.raw:
            self.raw[2].append(data)

    def handle_endtag(self, tag):
        if self.raw and tag == self.raw[0]:
            self.finish()

    def finish(self):
        tag, pairs, data = self.raw
        self.raw = None
        text = ''.join(data)
        if tag == 'script':
            self.found.append(('element', 'script', repr(pairs) + text))
        else:
            self.found += [('css', 'style', load) for load in css_loads(text)]

    def handle_pi(self, data):
        # Any <? a server may honour (short tags included); an XML prolog aside.
        if not re.match(r'xml\s', data, re.I):
            self.found.append(('php', 'pi', data))

    def close(self):
        super().close()
        if self.raw:
            self.finish()


def unsafe(text):
    """[(feature name, the feature)] of what in markup runs code in a
    visitor's browser, with each stretch of raw HTML a template holds outside
    every block. A Custom HTML block is markup like any other: what it holds
    is judged, not that it is one."""
    parser = Features()
    try:
        parser.feed(text)
        parser.close()
    except Exception:
        return [('unparsable markup', ('parse', text))]
    found = [(FEATURES[kind], (kind, where, value)) for kind, where, value in parser.found]
    if DELIMITER.search(text):
        depth, at = 0, 0
        for match in DELIMITER.finditer(text):
            if depth == 0 and text[at:match.start()].strip():
                found.append((FEATURES['raw'], ('raw', '', text[at:match.start()].strip())))
            closer, _, _, void = match.groups()
            depth += -1 if closer else (0 if void else 1)
            at = match.end()
        if depth == 0 and text[at:].strip():
            found.append((FEATURES['raw'], ('raw', '', text[at:].strip())))
    return found


def extra(before, after):
    """The items of `after` that `before` does not hold as many times, byte
    for byte (a multiset difference, in `after`'s order)."""
    have = {}
    for item in before:
        have[item] = have.get(item, 0) + 1
    found = []
    for item in after:
        if have.get(item, 0):
            have[item] -= 1
        else:
            found.append(item)
    return found


def element_breaks(text, allow):
    """h2wp/element blocks with a tag or an attribute the converter never
    emits (its element allowlist), or a link WordPress would not save."""
    tags = set(allow.get('tags', [])) | set(allow.get('svgTags', []))
    names = set(allow.get('attributes', []))
    patterns = [re.compile(p) for p in allow.get('attributePatterns', [])]
    found = []
    for match in DELIMITER.finditer(text):
        closer, name, attrs, _ = match.groups()
        if closer or name != 'h2wp/element' or not attrs:
            continue
        try:
            value = json.loads(attrs)
        except ValueError:
            continue
        tag = value.get('tagName', 'div')
        if tag not in tags:
            found.append(f'<{tag}>')
        for key, item in (value.get('htmlAttributes') or {}).items():
            if key not in names and not any(p.fullmatch(key) for p in patterns):
                found.append(f'{key}=')
            elif key in ('href', 'src', 'action', 'formaction', 'xlink:href', 'poster', 'data') and isinstance(item, str) and (
                    not SAVED_URL.fullmatch(decoded_url(item)) or unsafe_url(item)):
                found.append(f'{key}="{item[:40]}"')
    return found


URL_FIELD = re.compile(r'(url|href|link|src|action)$', re.I)


def json_strings(value, path):
    """(path, text) of every string in a JSON value; an entry of a list is
    named by its key or slug when it has one, so reordering renames nothing.
    A field that holds a link is read as the link it becomes."""
    if isinstance(value, dict):
        for key, item in value.items():
            yield from json_strings(item, f'{path}.{key}')
    elif isinstance(value, list):
        for index, item in enumerate(value):
            name = item.get('key') or item.get('slug') if isinstance(item, dict) else None
            yield from json_strings(item, f'{path}[{name if isinstance(name, str) else index}]')
    elif isinstance(value, str):
        field = path.rsplit('.', 1)[-1]
        yield path, (f'<a href="{html.escape(value, quote=True)}"></a>' if URL_FIELD.search(field) else value)


def markup_units(rel, data):
    """{unit: markup} of one file: the file itself, or every string field of
    a JSON file (a page's content and its title alike: core/post-title prints
    the title as it is stored)."""
    text = data.decode('utf-8', 'replace')
    if rel.endswith('.json'):
        try:
            value = json.loads(text)
        except ValueError:
            return {rel: text}
        return {f'{rel} {path}': item for path, item in json_strings(value, '')}
    return {rel: text}


def style_header(text):
    """The style.css header fields a live fix keeps (all but Version and Description)."""
    match = re.match(r'\s*/\*(.*?)\*/', text, re.S)
    fields = dict(re.findall(r'^\s*([A-Za-z][A-Za-z ]*?)\s*:\s*(.*?)\s*$', match.group(1), re.M)) if match else {}
    return {k: v for k, v in fields.items() if k not in ('Version', 'Description')}


def file_checks(lay, base_files, rel, now, allow):
    """Refusals for one file a fix writes (its bytes `now`), against its base
    version: its kind, the markup it holds, its PHP, its styles."""
    target = lay['target']
    if not editable(target, rel):
        return [row('file-type', f'{rel}: a live fix does not add or change this kind of file')]
    rows, was = [], stored(lay, base_files.get(rel))
    if rel.endswith(('.html', '.json', '.svg', '.php')):
        units_before = markup_units(rel, was) if was else {}
        for unit, text in markup_units(rel, now).items():
            more = list(dict.fromkeys(name for name, _ in extra(unsafe(units_before.get(unit, '')), unsafe(text))))
            if more:
                rows.append(row('unsafe-markup', f'{unit}: the fix adds or changes ' + ', '.join(more)))
            bad = extra(element_breaks(units_before.get(unit, ''), allow), element_breaks(text, allow)) if allow else []
            if bad:
                rows.append(row('element', f'{unit}: h2wp/element with ' + ', '.join(list(dict.fromkeys(bad))[:5])))
    breaks = markup_breaks(rel, now)
    if breaks:
        rows.append(row('block-grammar', 'Block markup that WordPress would misread: ' + '; '.join(breaks[:5])))
    if rel.endswith('.php'):
        code = php_outside_markup(now.decode('utf-8', 'replace'), was.decode('utf-8', 'replace'))
        if code:
            rows.append(row('php', f'{rel}: PHP beyond the pattern\'s own: ' + '; '.join(code[:3])))
    if rel.endswith('.css') or rel == 'theme.json':
        def loads(data):
            if rel.endswith('.css'):
                return css_loads(data.decode('utf-8', 'replace'))
            return [load for _, text in markup_units(rel, data).items() for load in css_loads(text)] if data else []
        more = extra(loads(was), loads(now))
        if more:
            rows.append(row('external-css', f'{rel}: the fix adds or changes ' + ', '.join(more[:3])[:200]))
    if rel == 'style.css' and was and style_header(now.decode('utf-8', 'replace')) != style_header(was.decode('utf-8', 'replace')):
        rows.append(row('style-header', 'style.css: the header changed beyond Version and Description'))
    return rows


def element_allowlist(lay):
    """The converter's element allowlist, as the theme ships it (owned, so the base's)."""
    return read(lay['theme'] / 'element-allowlist.json', {}) if lay['target'] == 'gutenberg' else {}


def content_checks(lay, base, hashes, changed):
    """Refusals for what the changed files hold, against their base versions."""
    rows, allow = [], element_allowlist(lay)
    for rel in changed['added'] + changed['modified']:
        if not compiler_owned(lay['target'], rel):
            rows += file_checks(lay, base['files'], rel, (lay['theme'] / rel).read_bytes(), allow)
    return rows


def listed_scripts(lay, base):
    """The theme files the contract config loads as scripts, whatever their
    extension: a change to one is a script change."""
    config = json.loads(stored(lay, base['files'].get('content/config.json')) or b'{}')
    found = set()
    for key, value in config.items():
        if 'cripts' not in key:
            continue
        for item in (value.values() if isinstance(value, dict) else [value]):
            for path in (item if isinstance(item, list) else [item]):
                if isinstance(path, str):
                    found.add(path.lstrip('/'))
    return found


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def file_hashes(root):
    """{relative path: sha256} of every file under root; a symlink refuses."""
    root, found = Path(root), {}
    for path in sorted(root.rglob('*')):
        if path.is_symlink():
            raise Refused('symlink', f'The theme contains a symbolic link: {path.relative_to(root)}')
        if path.is_file():
            found[path.relative_to(root).as_posix()] = sha(path)
    return found


def digest(hashes, skip=('screenshot.png',)):
    """gutenberg-package.py's theme_digest over precomputed file hashes
    (screenshot.png is bound separately there, and here)."""
    hashed = hashlib.sha256()
    for rel in sorted(hashes):
        if rel in skip:
            continue
        hashed.update(rel.encode() + b'\0')
        hashed.update(bytes.fromhex(hashes[rel]))
    return hashed.hexdigest()


# What a source tree holds that is not the source: installed dependencies,
# version control and build caches (an npm project's node_modules/.bin is
# symbolic links, and its size is not the conversion's business).
NOT_SOURCE = frozenset({'node_modules', '.git', '.hg', '.svn', '.cache', '.astro', '.next', '.nuxt', '.svelte-kit',
                        '.turbo', '.parcel-cache', '.vite', '__pycache__', '.DS_Store'})


def tree_digest(path):
    """The digest of a conversion input (a file or a folder): every file by
    its bytes and every symbolic link by where it points, dependencies and
    caches aside. Unlike the theme, an input may hold links."""
    path = Path(path)
    if path.is_symlink():
        return hashlib.sha256(b'link\0' + os.readlink(path).encode()).hexdigest()
    if path.is_file():
        return sha(path)
    if not path.is_dir():
        return None
    hashed = hashlib.sha256()
    for folder, dirs, files in os.walk(path, followlinks=False):
        dirs[:] = sorted(d for d in dirs if d not in NOT_SOURCE)
        here = Path(folder)
        entries = [(name, 'file') for name in files if name not in NOT_SOURCE]
        entries += [(name, 'link') for name in dirs if (here / name).is_symlink()]
        dirs[:] = [d for d in dirs if not (here / d).is_symlink()]
        for name, _ in sorted(entries):
            item = here / name
            rel = item.relative_to(path).as_posix()
            value = b'link\0' + os.readlink(item).encode() if item.is_symlink() else bytes.fromhex(sha(item)) if item.is_file() else b'other'
            hashed.update(rel.encode() + b'\0' + value)
    return hashed.hexdigest()


def read(path, default=None):
    try:
        return json.loads(Path(path).read_text())
    except (OSError, ValueError):
        return default


def write(path, value):
    Path(path).write_text(json.dumps(value, indent=2, ensure_ascii=False) + '\n')


def canonical(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(',', ':'), ensure_ascii=False).encode()).hexdigest()


def stamp():
    return time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())


def theme_dir(ws, slug):
    """{workspace}/theme/<slug>, for a slug that can only name a folder there."""
    if not isinstance(slug, str) or not SLUG.fullmatch(slug):
        raise Refused('slug', f'{slug!r} is not a theme slug')
    theme = Path(ws) / 'theme' / slug
    if theme.is_symlink() or (Path(ws) / 'theme').is_symlink() or theme.resolve().parent != (Path(ws) / 'theme').resolve():
        raise Refused('slug', f'theme/{slug} is a link, or not a folder directly in the workspace theme folder')
    return theme


def layout(ws):
    """The workspace's manifest, theme folder and target."""
    ws = Path(ws).resolve()
    manifest = read(ws / 'conversion-manifest.json')
    if not isinstance(manifest, dict) or not (manifest.get('site') or {}).get('slug'):
        raise Refused('no-workspace', f'{ws} has no conversion-manifest.json with site.slug')
    slug = manifest['site']['slug']
    target = 'gutenberg' if manifest.get('schema') == 'html2wp/2' or manifest.get('target') == 'gutenberg' else 'html'
    theme = theme_dir(ws, slug)
    if not theme.is_dir():
        raise Refused('no-theme', f'No theme at theme/{slug}')
    return {'ws': ws, 'manifest': manifest, 'slug': slug, 'target': target, 'theme': theme}


def inputs(ws, extra=None):
    """What the conversion consumed. A live fix changes none of it; the
    manifest's site.version is the one field a fix may set (the ZIP's name)."""
    manifest = read(ws / 'conversion-manifest.json') or {}
    manifest = {**manifest, 'site': {k: v for k, v in (manifest.get('site') or {}).items() if k != 'version'}}
    found = {'manifest': canonical(manifest)}
    for name in ('src', 'static-src', 'astro-project/dist', 'block-plan'):
        found[name] = tree_digest(ws / name)
    if extra:
        found['input'] = tree_digest(extra)
    return found


def module(name, file):
    spec = importlib.util.spec_from_file_location(name, HERE / file)
    loaded = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(loaded)
    return loaded


def newest(theme):
    return max((p.stat().st_mtime for p in Path(theme).rglob('*') if p.is_file()), default=0)


def base_evidence(lay, mode, hashes, report=None, base=None):
    """Proof that the theme as it is now passed its gate: a live fix starts
    only from a passed theme. The HTML finishing pass (html-finish.py) starts
    its theme phase from the F1 build instead: the manifest round whose
    structure came out green, measured on exactly these files."""
    ws, theme, now = lay['ws'], lay['theme'], digest(hashes)
    if base == 'delivered':
        # The round the finishing pass ended on (any phase, any rows): the
        # owner reviews it and may take it as it is or fix it live.
        source = Path(report) if report else ws / 'html-finish.json'
        state = read(source, {})
        rounds = state.get('rounds', [state]) if isinstance(state, dict) else state
        ended = [r for r in rounds if isinstance(r, dict) and r.get('counted') and r.get('themeDigest') == now]
        if lay['target'] == 'html' and ended:
            return {'kind': 'finish-round', 'round': ended[-1]['n'], 'failing': len(ended[-1].get('failing') or []),
                    'file': str(source), 'sha256': sha(source)}
        raise Refused('no-base', 'No counted round of the finishing pass measured these files')
    if base == 'f1':
        # The round history: the host's (--report names it) or the workspace's.
        source = Path(report) if report else ws / 'html-finish.json'
        state = read(source, {})
        rounds = state.get('rounds', [state]) if isinstance(state, dict) else state
        f1 = [r for r in rounds if r.get('counted') and r.get('phase') == 'F1']
        if lay['target'] == 'html' and f1 and not f1[-1]['structural'] and f1[-1]['themeDigest'] == now:
            return {'kind': 'f1-build', 'round': f1[-1]['n'], 'file': str(source), 'sha256': sha(source)}
        raise Refused('no-base', 'No F1 round of the finishing pass measured these files with a green structure')
    if lay['target'] == 'html':
        path = ws / 'verify-wp/report.json'
        value = read(path, {})
        if value.get('passed') is True and value.get('scope', 'full') == 'full' and path.stat().st_mtime >= newest(theme):
            return {'kind': 'verify-wp', 'file': 'verify-wp/report.json', 'sha256': sha(path)}
        raise Refused('no-base', 'The theme has no passing gates B/C (verify-wp report.json) newer than its files')
    if mode == 'flash':
        path = ws / 'quick-check.json'
        value = read(path, {})
        bound = value.get('themeDigest') == now if value.get('themeDigest') else path.stat().st_mtime >= newest(theme) if path.is_file() else False
        if value.get('passed') is True and bound:
            return {'kind': 'quick', 'file': 'quick-check.json', 'sha256': sha(path)}
        raise Refused('no-base', 'The Flash theme has no passing quick check of these files')
    path = Path(report) if report else ws / 'gutenberg-verification.json'
    value = read(path, {})
    if value.get('passed') is True and value.get('scope', 'full') == 'full' and value.get('themeDigest') == now:
        return {'kind': 'gverify', 'file': str(path), 'sha256': sha(path)}
    accepted = read(ws / 'accepted-differences.json', {})
    if (path.is_file() and accepted.get('schema') == 'h2wp-accepted-differences/1' and accepted.get('reportSha256') == sha(path)
            and accepted.get('themeDigest') == value.get('themeDigest') == now):
        return {'kind': 'accepted', 'file': str(path), 'sha256': sha(path)}
    raise Refused('no-base', 'The theme has no passing full check (gverify) of these files, and no accepted differences')


def save_marker(ws, marker):
    """live-fix.json, and its copy in .live-fix/: a deleted mark still
    stops a re-conversion that would discard the fixes."""
    write(Path(ws) / MARKER, marker)
    (Path(ws) / STORE).mkdir(exist_ok=True)
    write(Path(ws) / STORE / MARKER, marker)


def any_marker(ws):
    return read(Path(ws) / MARKER) or read(Path(ws) / STORE / MARKER)


def load(ws):
    marker = any_marker(ws)
    if marker is None:
        raise Refused('not-live', 'This workspace is not in live-fix mode')
    if marker.get('schema') != SCHEMA:
        raise Refused('marker', f'{MARKER} has an unknown schema')
    return marker


def open_cycle(marker):
    cycle = marker['cycles'][-1]
    if cycle.get('delivered'):
        raise Refused('delivered', 'The last live fix was delivered; the next one starts a new cycle')
    return cycle


def keep(lay, hashes, names=None):
    """Store the versions of these theme files (all by default) under
    .live-fix/objects/<sha256>, where revert finds them."""
    objects = lay['ws'] / STORE / 'objects'
    objects.mkdir(parents=True, exist_ok=True)
    for rel in names if names is not None else hashes:
        value = hashes.get(rel)
        if value and not (objects / value).is_file():
            shutil.copyfile(lay['theme'] / rel, objects / value)


def summary(marker):
    cycle = marker['cycles'][-1]
    return {'mode': marker['mode'], 'target': marker['target'], 'cycle': len(marker['cycles']), 'fixes': len(cycle['fixes']),
            'base': {k: v for k, v in cycle['base'].items() if k != 'files'}}


def start(args):
    lay = layout(args.workspace)
    hashes = file_hashes(lay['theme'])
    marker = any_marker(lay['ws'])
    if marker is not None:
        last = marker['cycles'][-1]
        if not last.get('delivered'):
            # Already live: starting again is the same fix going on.
            return {'ok': True, 'existing': True, **summary(marker)}
        # A fix after a delivery: its base is what was delivered, unchanged since.
        if digest(hashes) != last['delivered']['themeDigest']:
            raise Refused('changed-after-delivery', 'The theme changed after the last delivery, outside a live fix')
        evidence = {'kind': 'delivered', 'liveDigest': last['delivered']['liveDigest'], 'zip': last['delivered']['zip']}
    else:
        finishing = args.base == 'f1' or args.mode == 'finish'
        mode = 'full' if lay['target'] == 'html' else args.mode or ('flash' if module('h2wp_live_fix_package', 'gutenberg-package.py').flash_refusal(lay['theme']) else 'full')
        if lay['target'] == 'html' and args.mode == 'flash' and args.delivered:
            # An HTML Flash delivery as it is: the owner asks for fixes on what
            # Flash delivered, whatever its gates said (none ran, or red rows).
            # It certifies nothing; packaging certifies (the check) or says so
            # (--uncertified), as after the finishing pass.
            evidence = {'kind': 'flash-delivery', 'themeDigest': digest(hashes)}
        else:
            evidence = base_evidence(lay, mode, hashes, args.base_round or args.report,
                                     'delivered' if finishing and args.delivered else 'f1' if finishing else None)
        marker = {'schema': SCHEMA, 'target': lay['target'], 'mode': mode, 'slug': lay['slug'],
                  'input': str(Path(args.input).resolve()) if args.input else None, 'cycles': []}
    keep(lay, hashes)
    base = {'themeDigest': digest(hashes), 'files': hashes, 'inputs': inputs(lay['ws'], marker.get('input')), 'evidence': evidence,
            'liveDigest': evidence.get('liveDigest')}
    marker['cycles'].append({'startedAt': stamp(), 'base': base, 'fixes': [], 'delivered': None})
    save_marker(lay['ws'], marker)
    for name in (STATE, CHECK):
        (lay['ws'] / name).unlink(missing_ok=True)
    return {'ok': True, 'existing': False, **summary(marker)}


def changes(base_files, hashes):
    added = sorted(set(hashes) - set(base_files))
    removed = sorted(set(base_files) - set(hashes))
    modified = sorted(rel for rel in set(hashes) & set(base_files) if hashes[rel] != base_files[rel])
    return {'added': added, 'modified': modified, 'removed': removed}


def logged(cycle, upto=None):
    """{path: sha256 or None (removed)} as the fix log recorded it, after
    `upto` fixes (all by default), on top of the base."""
    found = dict(cycle['base']['files'])
    for fix in cycle['fixes'][:upto]:
        found.update(fix['files'])
    return {rel: value for rel, value in found.items() if value}


def scan(path):
    """Flash's script scan (gutenberg-plan.py flash_scan) on a theme script:
    None when Flash would list it unreviewed, else why not."""
    if path.suffix != '.js':
        return 'not a classic .js script'
    return scan_text(path.read_text(errors='replace'), path.stat().st_size)


def scan_text(code, size):
    plan = module('h2wp_live_fix_plan', 'gutenberg-plan.py')
    if size > plan.FLASH_SCRIPT_BYTES:
        return 'larger than 32 KB, too large for an automatic scan'
    return next((reason for pattern, reason in plan.FLASH_REFUSALS if pattern.search(code)), None)


# WordPress's block delimiter (parse_blocks' grammar): a comment that opens,
# closes or is void, a name, and at most one JSON object of attributes.
DELIMITER = re.compile(r'<!--\s+(/)?wp:([a-z][a-z0-9_-]*(?:/[a-z][a-z0-9_-]*)?)\s+(\{(?:(?!\}\s+/?-->).)*\}\s+)?(/)?-->', re.S)
LOOSE = re.compile(r'<!--\s*/?\s*wp:')


def grammar(markup):
    """The first break of the block grammar in markup, or None: a delimiter
    that does not parse, attributes that are not one object, or blocks that
    do not open and close in order (an eaten closer turns the rest of the
    page into children, silently)."""
    stack, at = [], 0
    for match in DELIMITER.finditer(markup):
        loose = LOOSE.search(markup, at, match.start())
        if loose:
            return f'a delimiter that does not parse at offset {loose.start()}: {markup[loose.start():loose.start() + 60]!r}'
        at = match.end()
        closer, name, attrs, void = match.groups()
        if attrs is not None:
            try:
                value = json.loads(attrs)
            except ValueError:
                return f'the attributes of wp:{name} at offset {match.start()} are not JSON'
            if not isinstance(value, dict):
                return f'the attributes of wp:{name} at offset {match.start()} are not an object'
        if closer:
            if not stack or stack[-1] != name:
                return f'/wp:{name} at offset {match.start()} closes ' + (f'wp:{stack[-1]}' if stack else 'nothing')
            stack.pop()
        elif not void:
            stack.append(name)
    loose = LOOSE.search(markup, at)
    if loose:
        return f'a delimiter that does not parse at offset {loose.start()}: {markup[loose.start():loose.start() + 60]!r}'
    return f'wp:{stack[-1]} is never closed' if stack else None


def markup_breaks(rel, data):
    """Grammar breaks in one theme file that holds block markup."""
    if rel.endswith('.html') and rel.split('/')[0] in ('templates', 'parts', 'patterns'):
        found = grammar(data.decode('utf-8', 'replace'))
        return [f'{rel}: {found}'] if found else []
    if rel in ('content/content.json', 'content/patterns.json'):
        try:
            value = json.loads(data)
        except ValueError:
            return [f'{rel}: not JSON']
        entries = value.get('pages', []) if isinstance(value, dict) else value
        breaks = []
        for entry in entries if isinstance(entries, list) else []:
            if isinstance(entry, dict) and isinstance(entry.get('content'), str):
                found = grammar(entry['content'])
                if found:
                    breaks.append(f'{rel} {entry.get("key") or entry.get("slug")}: {found}')
        return breaks
    return []


def measure(ws):
    """The live state of the workspace's open fix, from its files alone."""
    lay, marker = layout(ws), load(ws)
    if marker.get('slug') != lay['slug']:
        raise Refused('slug', f'live-fix.json names the theme {marker.get("slug")!r}, the manifest {lay["slug"]!r}')
    cycle = open_cycle(marker)
    hashes = file_hashes(lay['theme'])
    base = cycle['base']
    changed = changes(base['files'], hashes)
    touched = changed['added'] + changed['modified'] + changed['removed']
    recorded = logged(cycle)
    reviews = {}
    for fix in cycle['fixes']:
        reviews.update(fix.get('scriptReviews') or {})
    refusals = []
    # By its path, or by what the file is now or was in the base.
    now = lambda rel: (lay['theme'] / rel).read_bytes()[:len(RECORDER)] if rel in hashes else b''
    owned = [rel for rel in touched if compiler_owned(lay['target'], rel, now(rel))
             or compiler_owned(lay['target'], rel, head_of(lay, base['files'].get(rel)))]
    if owned:
        refusals.append(row('compiler-owned', 'A live fix changed files the converter owns: ' + ', '.join(owned[:10])))
    refusals += content_checks(lay, base, hashes, {k: [rel for rel in v if rel not in owned] for k, v in changed.items()})
    moved = [name for name, value in inputs(lay['ws'], marker.get('input')).items() if base['inputs'].get(name) != value]
    if moved:
        refusals.append(row('inputs-changed', 'The conversion inputs changed during a live fix: ' + ', '.join(moved)))
    unlogged = sorted(rel for rel in set(recorded) | set(hashes) if recorded.get(rel) != hashes.get(rel))
    if unlogged:
        refusals.append(row('unlogged', 'Changes no fix records: ' + ', '.join(unlogged[:10])))
    scripts, listed = [], listed_scripts(lay, base)
    for rel in changed['added'] + changed['modified']:
        if not (rel.endswith(('.js', '.mjs')) or rel in listed) or rel in owned:
            continue
        item = {'path': rel}
        if marker['mode'] == 'flash':
            item['scan'] = scan(lay['theme'] / rel)
            if item['scan']:
                refusals.append(row('script-scan', f'{rel}: Flash would not list this script ({item["scan"]})'))
        else:
            review = reviews.get(rel) or {}
            item['review'] = review.get('reason') if review.get('sha256') == hashes[rel] else None
            if not item['review']:
                refusals.append(row('script-review', f'{rel} changed, and this version has no review'))
        scripts.append(item)
    screenshot = hashes.get('screenshot.png')
    bundle = hashes.get('content/content.json')
    live = canonical({'schema': SCHEMA, 'target': lay['target'], 'mode': marker['mode'], 'slug': lay['slug'],
                      'base': base.get('liveDigest') or base['themeDigest'], 'themeDigest': digest(hashes),
                      'screenshotSha256': screenshot, 'bundleSha256': bundle, 'fixes': cycle['fixes']})
    return {'lay': lay, 'marker': marker, 'cycle': cycle, 'hashes': hashes, 'refusals': refusals,
            'state': {'target': lay['target'], 'mode': marker['mode'], 'slug': lay['slug'], 'themeDigest': digest(hashes),
                      'screenshotSha256': screenshot, 'bundleSha256': bundle, 'changed': changed, 'scripts': scripts,
                      'fixes': len(cycle['fixes']), 'liveDigest': live}}


def record_fix(lay, marker, cycle, note, reviews=None):
    hashes = file_hashes(lay['theme'])
    recorded = logged(cycle)
    files = {rel: hashes.get(rel) for rel in sorted(set(hashes) | set(recorded)) if hashes.get(rel) != recorded.get(rel)}
    if not files and not reviews:
        raise Refused('nothing', 'Nothing changed since the last recorded fix')
    keep(lay, hashes, list(files))
    cycle['fixes'].append({'at': stamp(), 'note': note, 'files': files, **({'scriptReviews': reviews} if reviews else {})})
    save_marker(lay['ws'], marker)
    return {'ok': True, 'fix': len(cycle['fixes']), 'files': sorted(files)}


def log(args):
    if len(args.note.strip()) < REASON:
        raise Refused('note', 'A fix note says what was wrong and what the fix does')
    lay, marker = layout(args.workspace), load(args.workspace)
    cycle = open_cycle(marker)
    hashes = file_hashes(lay['theme'])
    reviews = {}
    for item in args.script_review or []:
        rel, _, reason = item.partition('=')
        if rel not in hashes or len(reason.strip()) < REASON:
            raise Refused('script-review', f'--script-review {item!r} names no theme script, or its reason is shorter than {REASON} characters')
        reviews[rel] = {'reason': reason.strip(), 'sha256': hashes[rel]}
    return record_fix(lay, marker, cycle, args.note.strip(), reviews)


def revert(args):
    """Put the theme back as it was after `--to` fixes (0: the base), from the
    stored versions, and record that as a fix of its own."""
    lay, marker = layout(args.workspace), load(args.workspace)
    cycle = open_cycle(marker)
    if not 0 <= args.to <= len(cycle['fixes']):
        raise Refused('revert', f'There are {len(cycle["fixes"])} fixes; --to {args.to} names none of them')
    wanted, hashes = logged(cycle, args.to), file_hashes(lay['theme'])
    objects = lay['ws'] / STORE / 'objects'
    # The log is a file anyone can edit: it names paths inside the theme and
    # stored versions by their hash, nothing else.
    root = lay['theme'].resolve()
    for rel, value in wanted.items():
        inside = (root / rel).resolve()
        if Path(rel).is_absolute() or '..' in Path(rel).parts or root not in inside.parents or not re.fullmatch(r'[0-9a-f]{64}', value or ''):
            raise Refused('marker', f'The fix log names {rel!r}, which is not a stored file inside the theme')
    for rel in sorted(set(wanted) | set(hashes)):
        path = lay['theme'] / rel
        if rel not in wanted:
            path.unlink()
        elif hashes.get(rel) != wanted[rel]:
            if not (objects / wanted[rel]).is_file() or sha(objects / wanted[rel]) != wanted[rel]:
                raise Refused('store', f'The stored version of {rel} is missing or not what the log names')
            path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(objects / wanted[rel], path)
    for folder in sorted((p for p in lay['theme'].rglob('*') if p.is_dir()), reverse=True):
        if not any(folder.iterdir()):
            folder.rmdir()
    note = 'Reverted the theme to ' + (f'fix {args.to}' if args.to else 'the base it passed as')
    return record_fix(lay, marker, cycle, note)


# What the preview holds, read through wp-cli: the installed theme's files, the
# content import (Gutenberg), and the customizations WordPress stores in the
# database for this theme (Site Editor templates and parts, user Styles),
# which a ZIP never carries.
FACTS_PHP = r'''
$root = get_stylesheet_directory(); $files = array();
if (is_dir($root)) {
  $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS));
  foreach ($it as $f) { $rel = str_replace('\\', '/', substr($f->getPathname(), strlen($root) + 1)); $files[$rel] = $f->isLink() ? 'symlink' : ($f->isFile() ? hash_file('sha256', $f->getPathname()) : null); }
}
$overrides = array();
$q = new WP_Query(array('post_type'=>array('wp_template','wp_template_part'),'post_status'=>'any','posts_per_page'=>-1,'no_found_rows'=>true,
  'tax_query'=>array(array('taxonomy'=>'wp_theme','field'=>'name','terms'=>get_stylesheet()))));
foreach ($q->posts as $p) { $overrides[] = array('type'=>$p->post_type,'slug'=>$p->post_name); }
if (class_exists('WP_Theme_JSON_Resolver') && method_exists('WP_Theme_JSON_Resolver','get_user_data_from_wp_global_styles')) {
  $user = WP_Theme_JSON_Resolver::get_user_data_from_wp_global_styles(wp_get_theme());
  $data = !empty($user['post_content']) ? json_decode($user['post_content'], true) : array();
  if (is_array($data)) { unset($data['version'], $data['isGlobalStylesUserThemeJSON']); if (array_filter($data)) { $overrides[] = array('type'=>'wp_global_styles','slug'=>get_stylesheet()); } }
}
echo wp_json_encode(array('stylesheet'=>get_stylesheet(),'files'=>$files,'overrides'=>$overrides,
  'import'=>function_exists('h2wp_gb_import_status') ? h2wp_gb_import_status() : null));
'''


def wp_cli(args):
    value = args.wp_cli
    if not value and args.env:
        value = read(args.env, {}).get('wpCli')
    if not value:
        return None
    if not isinstance(value, str) or not WP_CLI_SHAPES.fullmatch(' '.join(value.split())):
        raise Refused('env', f'{str(value)[:80]!r} is not the app runtime\'s wp-cli or a test-env container\'s')
    return shlex.split(value)


def facts(prefix):
    """The preview's facts, read between markers only this call knows:
    output the theme or a plugin prints on the way is never taken for them."""
    nonce = hashlib.sha256(os.urandom(32)).hexdigest()[:32]
    code = FACTS_PHP.replace("echo wp_json_encode(", f"echo '<h2wp-facts-{nonce}>', wp_json_encode(", 1).rstrip().rstrip(';') + f", '</h2wp-facts-{nonce}>';"
    result = subprocess.run([*prefix, 'eval', code], capture_output=True, text=True, timeout=300)
    found = re.findall(rf'<h2wp-facts-{nonce}>(.*?)</h2wp-facts-{nonce}>', result.stdout, re.S)
    if result.returncode != 0 or len(found) != 1:
        raise Refused('wp-cli', 'wp-cli could not read the preview: ' + (result.stderr or result.stdout)[-400:])
    return json.loads(found[0])


def judge_facts(measured, found):
    """Refusals for a preview that is not an install of exactly this theme and bundle."""
    state, lay, rows = measured['state'], measured['lay'], []
    if found.get('stylesheet') != lay['slug']:
        rows.append(row('active-theme', f'The preview runs {found.get("stylesheet")!r}, not {lay["slug"]!r}'))
    installed = {rel: value for rel, value in (found.get('files') or {}).items() if value}
    if 'symlink' in installed.values() or digest({k: v for k, v in installed.items() if v != 'symlink'}) != state['themeDigest']:
        wrong = sorted(rel for rel in set(installed) | set(measured['hashes']) if rel != 'screenshot.png' and installed.get(rel) != measured['hashes'].get(rel))
        rows.append(row('installed-differs', 'The preview runs other theme files than the workspace: ' + ', '.join(wrong[:10])))
    if installed.get('screenshot.png') != state['screenshotSha256']:
        rows.append(row('screenshot-differs', 'The installed screenshot.png is not the workspace one'))
    if lay['target'] == 'gutenberg':
        imported = found.get('import') or {}
        if (imported.get('complete') is not True or imported.get('errors') or not imported.get('bundleDigest')
                or imported.get('stateDigest') != imported.get('bundleDigest') or imported.get('bundleSha256') != state['bundleSha256']):
            rows.append(row('import', 'The preview content is not a complete import of this bundle: '
                            + json.dumps({k: imported.get(k) for k in ('phase', 'complete', 'pending', 'errors')})[:400]))
        edited = [item.get('key') for item in (imported.get('entities') or []) + (imported.get('menus') or [])
                  if isinstance(item, dict) and item.get('ownership') == 'owner-edited']
        if edited:
            rows.append(row('owner-edited', 'Content the owner edited in this preview: ' + ', '.join(map(str, edited[:10]))))
    overrides = found.get('overrides') or []
    if overrides:
        rows.append(row('db-overrides', 'WordPress stores customizations of this theme the ZIP will not carry: '
                        + ', '.join(f'{o.get("type")} {o.get("slug")}' for o in overrides[:10])))
    return rows


def check(args, certify=False):
    """A preview measured against the workspace. `certify` is the one on the
    fresh install the delivery is certified on; it alone is what packaging
    trusts, and a check of any other preview never replaces it."""
    measured = measure(args.workspace)
    rows = list(measured['refusals'])
    prefix = wp_cli(args)
    if certify and not prefix:
        raise Refused('env', 'A certifying check reads the fresh install')
    # wp eval boots the theme: never one that holds what a fix may not carry.
    held = [r for r in rows if r['code'] in ('file-type', 'php', 'compiler-owned', 'unsafe-markup', 'element', 'symlink')]
    found = facts(prefix) if prefix and not held else None
    if found:
        rows += judge_facts(measured, found)
    record = {'schema': STATE_SCHEMA, 'checkedAt': stamp(), 'certify': certify, 'preview': bool(found), 'passed': not rows,
              **measured['state'], 'refusals': rows,
              **({'facts': {'stylesheet': found.get('stylesheet'), 'overrides': found.get('overrides') or [],
                            'import': {k: (found.get('import') or {}).get(k) for k in ('complete', 'bundleDigest', 'stateDigest', 'bundleSha256')}}} if found else {})}
    # The certification may live where the agent cannot write (the app's
    # private folder): --state names it, and packaging reads it from there.
    write(Path(args.state) if certify and getattr(args, 'state', None) else measured['lay']['ws'] / (STATE if certify else CHECK), record)
    return {'ok': not rows, 'passed': not rows, 'certify': certify,
            **{k: record[k] for k in ('liveDigest', 'themeDigest', 'refusals', 'changed', 'fixes')}}


def host_round(history, now):
    """The latest counted round of the host's round history on exactly these
    files, or None."""
    value = read(history, []) if history else []
    rounds = value.get('rounds', []) if isinstance(value, dict) else value
    matching = [r for r in rounds if isinstance(r, dict) and r.get('counted') and r.get('rows', 0) > 0 and r.get('themeDigest') == now]
    return matching[-1] if matching else None


def verify_package(ws, report=None, quick=None, state_file=None, history=None, ledger=None, uncertified=False):
    """The receipt of a certified live fix, or Refused. Recomputes the live
    state from the files and holds it to what `certify` measured and to the
    certifying gate of the fix's mode. `uncertified` is the owner taking the
    theme without the final check: every rule of a fix still holds, and the
    receipt says, in so many words, that nothing certified it."""
    measured = measure(ws)
    if measured['refusals']:
        first = measured['refusals'][0]
        raise Refused(first['code'], first['message'])
    state, lay, marker = measured['state'], measured['lay'], measured['marker']
    if uncertified:
        gate = {'kind': 'uncertified', 'certified': False}
        passed = host_round(history, state['themeDigest']) if lay['target'] == 'html' else None
        if passed:
            gate.update(round=passed['n'], failing=passed.get('failing') or [])
        entries = read(ledger, {}) if ledger else {}
        if entries.get('themeDigest') == state['themeDigest']:
            gate.update(ledger=entries.get('entries') or [], wooDefaults=entries.get('wooDefaults') or [], staticNav=entries.get('staticNav') or [])
        return receipt_of(measured, gate)
    record = read(Path(state_file) if state_file else lay['ws'] / STATE, {})
    if record.get('schema') != STATE_SCHEMA or record.get('certify') is not True:
        raise Refused('not-certified', 'No certifying check of the fixed theme')
    if record.get('liveDigest') != state['liveDigest']:
        raise Refused('state-stale', 'The theme or its fix log changed after the certifying check')
    if record.get('passed') is not True:
        raise Refused('not-certified', 'The certifying check refused: ' + '; '.join(r['message'] for r in record.get('refusals', [])[:3]))
    theme, mode, now = lay['theme'], marker['mode'], state['themeDigest']
    if lay['target'] == 'html':
        # Certified: gates B/C passed on these files, or a round the host
        # recorded (its gates, its reports) that passed on these files. A
        # ledger never certifies: with one, the theme is delivered WITH a
        # ledger, marked not certified, as documented differences are.
        path = Path(report) if report else lay['ws'] / 'verify-wp/report.json'
        value = read(path, {})
        passed = host_round(history, now)
        entries = (read(ledger, {}) if ledger else {})
        if value.get('passed') is True and value.get('scope', 'full') == 'full' and path.stat().st_mtime >= newest(theme):
            gate = {'kind': 'verify-wp', 'sha256': sha(path)}
        elif passed and passed.get('passed') is True and not passed.get('failing'):
            gate = {'kind': 'finish-passed', 'round': passed['n'], 'sha256': sha(history)}
        elif ledger:
            failing = {row.get('id') for row in (passed or {}).get('failing') or []}
            rows = entries.get('entries') or []
            if not (entries.get('schema') == 'h2wp-html-finish-ledger/1' and passed and entries.get('round') == passed['n']
                    and entries.get('themeDigest') == now and rows and {row.get('id') for row in rows} == failing
                    and all(row.get('cause') and row.get('lever') and row.get('note') for row in rows)):
                raise Refused('certification', 'The ledger does not list exactly the rows a host-recorded round of these files left failing')
            gate = {'kind': 'ledger', 'certified': False, 'round': passed['n'], 'sha256': sha(ledger), 'ledger': rows,
                    'wooDefaults': entries.get('wooDefaults') or [], 'staticNav': entries.get('staticNav') or []}
        else:
            raise Refused('certification', 'No passing gates B/C of the fixed theme, no passing host-recorded round of these files, and no ledger')
    elif mode == 'flash':
        path = Path(quick) if quick else lay['ws'] / 'quick-check.json'
        value = read(path, {})
        if not (value.get('passed') is True and value.get('liveDigest') == state['liveDigest']):
            raise Refused('certification', f'No passing quick check bound to this live state ({path.name} must record its liveDigest)')
        gate = {'kind': 'quick', 'sha256': sha(path)}
    else:
        path = Path(report) if report else lay['ws'] / 'gutenberg-verification.json'
        value = read(path, {})
        accepted = read(lay['ws'] / 'accepted-differences.json', {})
        passed = value.get('passed') is True and value.get('scope', 'full') == 'full'
        accept = (accepted.get('schema') == 'h2wp-accepted-differences/1' and path.is_file() and accepted.get('reportSha256') == sha(path)
                  and accepted.get('themeDigest') == value.get('themeDigest'))
        if value.get('themeDigest') != now or not (passed or accept):
            raise Refused('certification', 'No full check (gverify) of the fixed theme that passed or whose differences were accepted')
        edited = [item.get('key') for item in ((value.get('import') or {}).get('entities') or [])
                  if isinstance(item, dict) and item.get('ownership') == 'owner-edited']
        if edited:
            raise Refused('owner-edited', 'The full check ran on content the owner edited: ' + ', '.join(map(str, edited[:10])))
        gate = {'kind': 'gverify' if passed else 'accepted', 'sha256': sha(path)}
    return receipt_of(measured, gate)


def receipt_of(measured, gate):
    state, lay, marker = measured['state'], measured['lay'], measured['marker']
    certified = gate.get('certified', gate['kind'] != 'accepted')
    gate = {k: v for k, v in gate.items() if k != 'certified'}
    delivery = 'certified' if certified else {'ledger': 'ledger', 'uncertified': 'uncertified'}.get(gate['kind'], 'documented-differences')
    cycle = measured['cycle']
    notes = {}
    if lay['target'] == 'html':
        # Named on every delivery, certified too: notes, not failing rows.
        finish = module('h2wp_live_fix_finish', 'html-finish.py')
        notes = {'notes': {'wooDefaults': finish.woo_defaults(read(lay['ws'] / 'conversion-manifest.json') or {}),
                           'staticNav': finish.static_navs(lay['ws'])}}
    return {'schema': 'h2wp-live-fix-receipt/1', 'slug': lay['slug'], 'target': lay['target'], 'mode': marker['mode'],
            'certified': certified, 'delivery': delivery,
            'liveDigest': state['liveDigest'], 'themeDigest': state['themeDigest'], 'screenshotSha256': state['screenshotSha256'],
            'bundleSha256': state['bundleSha256'], 'base': {k: v for k, v in cycle['base'].items() if k in ('themeDigest', 'liveDigest', 'evidence')},
            'certification': gate, 'fixes': cycle['fixes'], **notes}


# What a packer leaves out of a theme ZIP: junk anywhere, build residue at the
# root (make-zip.sh's rsync excludes; gutenberg-package.py and the app's packer
# leave out less).
ROOT_RESIDUE = re.compile(r'(\.git[^/]*|node_modules|src)(/.*)?|package(-lock)?\.json|composer\.(json|lock)|phpcs\.xml'
                          r'|[^/]*\.config\.js|\.editorconfig|\.eslintrc[^/]*|\.stylelintrc[^/]*')


def junk(rel):
    parts = rel.split('/')
    return any(p == '.DS_Store' or p == '__MACOSX' or p.startswith('._') for p in parts) or bool(ROOT_RESIDUE.fullmatch(rel))


def packed_differences(zip_path, slug, hashes):
    """Paths where the ZIP is not the certified theme: a member that is not
    that file's bytes, or a theme file (other than packer junk) left out."""
    with zipfile.ZipFile(zip_path) as archive:
        infos = archive.infolist()
        names = [info.filename for info in infos]
        # What an extractor could take for another file than the one hashed:
        # a name twice (read() hashes the last), a symbolic link, a bomb.
        if (len(names) != len(set(names)) or len(infos) > ZIP_MEMBERS or sum(i.file_size for i in infos) > ZIP_BYTES
                or any((info.external_attr >> 16) & 0o170000 == 0o120000 for info in infos)):
            return ['the archive holds a duplicate name, a symbolic link, or more than it should']
        members = {name[len(slug) + 1:]: hashlib.sha256(archive.read(name)).hexdigest()
                   for name in names if name.startswith(slug + '/') and not name.endswith('/')}
        stray = [name for name in names if not name.startswith(slug + '/')]
    wrong = [rel for rel, value in members.items() if hashes.get(rel) != value]
    missing = [rel for rel in hashes if rel not in members and not junk(rel)]
    return sorted(stray + wrong + missing)


def deliver(ws, zip_path, receipt):
    """After the ZIP exists: it holds exactly the certified theme; the receipt
    goes beside it and the cycle is closed (the next fix chains from it)."""
    zip_path = Path(zip_path).resolve()
    lay, marker = layout(ws), load(ws)
    hashes = file_hashes(lay['theme'])
    differ = packed_differences(zip_path, receipt['slug'], hashes)
    if digest(hashes) != receipt['themeDigest'] or differ:
        raise Refused('zip', 'The ZIP does not hold the certified theme' + (': ' + ', '.join(differ[:10]) if differ else ''))
    receipt = {**receipt, 'zip': zip_path.name, 'zipSha256': sha(zip_path), 'deliveredAt': stamp(),
               **({'experimental': True, 'note': 'Gutenberg block themes are experimental in this version: full Gutenberg support comes next.'}
                  if receipt.get('target') == 'gutenberg' else {})}
    write(zip_path.with_name(zip_path.stem + '.live-fix.json'), receipt)
    cycle = open_cycle(marker)
    cycle['delivered'] = {k: receipt[k] for k in ('liveDigest', 'themeDigest', 'zip', 'zipSha256', 'deliveredAt', 'certified', 'delivery')}
    save_marker(lay['ws'], marker)
    return receipt


def marked_theme(ws, marker):
    """The theme folder live-fix.json names, only when it is the manifest's."""
    manifest = read(ws / 'conversion-manifest.json') or {}
    if marker.get('slug') != (manifest.get('site') or {}).get('slug'):
        raise Refused('slug', f'live-fix.json names the theme {marker.get("slug")!r}, the manifest another')
    return theme_dir(ws, marker['slug'])


def carries_fixes(ws, marker):
    theme = marked_theme(ws, marker)
    last = marker['cycles'][-1] if marker.get('cycles') else {}
    edited = theme.is_dir() and not last.get('delivered') and digest(file_hashes(theme)) != last.get('base', {}).get('themeDigest')
    return edited or any(cycle.get('fixes') for cycle in marker.get('cycles', []))


def check_path(args):
    """May a live fix write these theme paths? By path and file type (and,
    for a file the theme has, by what it is): the app asks before each write."""
    lay = layout(args.workspace)
    marker = any_marker(lay['ws'])
    base = marker['cycles'][-1]['base']['files'] if marker and marker.get('cycles') else {}
    if args.content_file and len(args.path) != 1:
        raise Refused('file-type', '--content-file judges the bytes of one path')
    rows = []
    for rel in args.path:
        clean = rel.replace('\\', '/')
        if (not rel or rel != clean or clean.startswith('/') or '\0' in clean
                or any(part in ('', '.', '..') for part in clean.split('/'))):
            rows.append({**row('file-type', f'{rel!r} is not a path inside the theme'), 'path': rel})
            continue
        path = lay['theme'] / clean
        content = Path(args.content_file).read_bytes() if args.content_file else None
        head = (content if content is not None else path.read_bytes() if path.is_file() and not path.is_symlink() else b'')[:len(RECORDER)]
        if compiler_owned(lay['target'], clean, head) or compiler_owned(lay['target'], clean, head_of(lay, base.get(clean))):
            rows.append({**row('compiler-owned', f'{clean}: the converter owns this file'), 'path': rel})
        elif content is not None:
            # The bytes the agent wants to write, judged as status will judge them.
            found = file_checks(lay, base, clean, content, element_allowlist(lay))
            if marker and marker.get('mode') == 'flash' and clean.endswith('.js') and not found:
                reason = scan_text(content.decode('utf-8', 'replace'), len(content))
                if reason:
                    found.append(row('script-scan', f'{clean}: Flash would not list this script ({reason})'))
            rows += [{**item, 'path': rel} for item in found]
        elif not editable(lay['target'], clean):
            rows.append({**row('file-type', f'{clean}: a live fix does not add or change this kind of file'), 'path': rel})
    return {'ok': not rows, 'refusals': rows}


def guard(args):
    """A re-conversion replaces the theme: with live fixes in it, that
    discards them. Refused; an unused mark is simply cleared."""
    ws = Path(args.workspace).resolve()
    marker = any_marker(ws)
    if marker is None:
        return {'ok': True, 'live': False}
    if carries_fixes(ws, marker):
        raise Refused('live-fixes', 'This theme carries live fixes; converting again replaces the theme and discards them')
    for name in (MARKER, STATE, CHECK):
        (ws / name).unlink(missing_ok=True)
    shutil.rmtree(ws / STORE, ignore_errors=True)
    return {'ok': True, 'live': False}


def discard(args):
    """The owner's choice: the live fixes leave the workspace (a conversion
    may then run), kept beside it with their log, never deleted."""
    ws = Path(args.workspace).resolve()
    marker = any_marker(ws)
    if marker is None:
        return {'ok': True, 'live': False}
    if not carries_fixes(ws, marker):
        return guard(args)
    theme = marked_theme(ws, marker)
    kept = ws / time.strftime('theme.live-fixes-%Y%m%dT%H%M%SZ', time.gmtime())
    kept.mkdir()
    if theme.is_dir():
        shutil.move(str(theme), str(kept / marker['slug']))
    for name in (MARKER, STATE, CHECK, STORE):
        if (ws / name).exists():
            shutil.move(str(ws / name), str(kept / name))
    return {'ok': True, 'live': False, 'kept': str(kept)}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='command', required=True)
    sub.add_parser('levers')
    for name in ('start', 'log', 'revert', 'status', 'check', 'certify', 'check-path', 'verify-package', 'deliver', 'guard', 'discard'):
        command = sub.add_parser(name)
        command.add_argument('--workspace', required=True)
        if name == 'start':
            command.add_argument('--mode', choices=('flash', 'full', 'finish'))
            command.add_argument('--base', choices=('f1',), help='the HTML finishing pass: start from the F1 build (html-finish.py)')
            command.add_argument('--base-round', help="the host's F1 round (one round's JSON, or its round history); --mode finish")
            command.add_argument('--delivered', action='store_true',
                                 help='--mode finish: the base is the round the pass ended on, whatever its rows (the owner reviews it); '
                                      '--mode flash on an HTML theme: the base is the Flash delivery as it is')
            command.add_argument('--report')
            command.add_argument('--input')
        if name == 'log':
            command.add_argument('--note', required=True)
            command.add_argument('--script-review', action='append')
        if name == 'revert':
            command.add_argument('--to', type=int, required=True)
        if name == 'check-path':
            command.add_argument('--path', action='append', required=True, help='a theme-relative path; repeat for several')
            command.add_argument('--content-file', help='the bytes about to be written to the one --path, judged as status judges them')
        if name in ('check', 'certify'):
            command.add_argument('--wp-cli')
            command.add_argument('--env')
            command.add_argument('--state', help='where certify writes the certification (default: the workspace)')
        if name == 'check':
            command.add_argument('--certify', action='store_true', help='the same as the certify command')
        if name in ('verify-package', 'deliver'):
            command.add_argument('--report')
            command.add_argument('--quick')
            command.add_argument('--state', help='the certification certify wrote (default: the workspace)')
            command.add_argument('--history', help="HTML: the host's round history of the finishing pass (html-finish.py)")
            command.add_argument('--ledger', help='HTML: the ledger html-finish.py wrote from that history (delivery WITH a ledger, not certified)')
            command.add_argument('--uncertified', action='store_true',
                                 help='the owner takes the theme without the final check: every rule of a fix holds, the receipt says certified:false')
        if name == 'deliver':
            command.add_argument('--zip', required=True)
    args = parser.parse_args(argv)
    try:
        if args.command == 'levers':
            result = {'ok': True, 'levers': LEVERS}
        elif args.command == 'start':
            result = start(args)
        elif args.command == 'log':
            result = log(args)
        elif args.command == 'revert':
            result = revert(args)
        elif args.command == 'status':
            measured = measure(args.workspace)
            result = {'ok': not measured['refusals'], **measured['state'], 'refusals': measured['refusals']}
        elif args.command in ('check', 'certify'):
            result = check(args, certify=args.command == 'certify' or args.certify)
        elif args.command == 'verify-package':
            result = {'ok': True, **verify_package(args.workspace, args.report, args.quick, args.state, args.history, args.ledger, args.uncertified)}
        elif args.command == 'deliver':
            result = {'ok': True, **deliver(args.workspace, args.zip, verify_package(args.workspace, args.report, args.quick, args.state, args.history, args.ledger, args.uncertified))}
        elif args.command == 'check-path':
            result = check_path(args)
        elif args.command == 'guard':
            result = guard(args)
        else:
            result = discard(args)
    except Refused as refused:
        result = {'ok': False, 'refusals': [refused.row]}
    print(json.dumps(result, indent=2, ensure_ascii=False))
    return 0 if result.get('ok') else 1


if __name__ == '__main__':
    sys.exit(main())
